[package]
name = "lab"
version = "0.1.0"
authors = ["Hendry Lim <myhendry@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.3"
regex = "0.2"
reqwest = "0.8.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"